// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWhOIh67S2qfwGX7-QwIyGQp64-HzTwFM',
    appId: '1:511382039985:web:3ccf134d783b365d2a2190',
    messagingSenderId: '511382039985',
    projectId: 'reyhowley',
    authDomain: 'reyhowley.firebaseapp.com',
    storageBucket: 'reyhowley.firebasestorage.app',
    measurementId: 'G-6VW72LL8CW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBje9-Lg6_qDS-mkKSVj0XPIyRM2ubGocM',
    appId: '1:511382039985:android:2f1c90d8cf2b8eb92a2190',
    messagingSenderId: '511382039985',
    projectId: 'reyhowley',
    storageBucket: 'reyhowley.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeQzoiSp3QvZmD2iTzRweBLfHrCz_EBV8',
    appId: '1:511382039985:ios:900053693ddf453b2a2190',
    messagingSenderId: '511382039985',
    projectId: 'reyhowley',
    storageBucket: 'reyhowley.firebasestorage.app',
    iosBundleId: 'com.reyhowley.app',
  );

}